class LogoMain{
	public static void main(String[] args)
	{
		System.out.println("Invoking main in LogoMain");
		Logo logo=new Logo();
		System.out.println(logo.color);
		System.out.println(logo.shape);
		System.out.println(logo.name);
		System.out.println(logo.type);
		System.out.println(logo.lenght);
		System.out.println(logo.width);
		System.out.println(logo.use);
		System.out.println(logo.color1);
		System.out.println(logo.type1);
		System.out.println("++++++++++++++++++++");
		Logo logo1=new Logo("White");
		System.out.println(logo1.color);
		System.out.println("++++++++++++++++++++");
		Logo logo2=new Logo("White","Round");
		System.out.println(logo2.color);
		System.out.println(logo2.shape);
		System.out.println("++++++++++++++++++++");
		Logo logo3=new Logo("White","Round","X-Workz");
		System.out.println(logo3.color);
		System.out.println(logo3.shape);
		System.out.println(logo3.name);
		System.out.println("++++++++++++++++++++");
		Logo logo4=new Logo("White","Round","X-Workz","Company");
		System.out.println(logo4.color);
		System.out.println(logo4.shape);
		System.out.println(logo4.name);
		System.out.println(logo4.type);
		System.out.println("++++++++++++++++++++");
		Logo logo5=new Logo("White","Round","X-Workz","Company",5.5f);
		System.out.println(logo5.color);
		System.out.println(logo5.shape);
		System.out.println(logo5.name);
		System.out.println(logo5.type);
		System.out.println(logo5.lenght);
		System.out.println("++++++++++++++++++++");
		Logo logo6=new Logo("White","Round","X-Workz","Company",5.5f,3.5f);
		System.out.println(logo6.color);
		System.out.println(logo6.shape);
		System.out.println(logo6.name);
		System.out.println(logo6.type);
		System.out.println(logo6.lenght);
		System.out.println(logo6.width);
		System.out.println("++++++++++++++++++++");
		Logo logo7=new Logo("White","Round","X-Workz","Company",5.5f,3.5f,"Information");
		System.out.println(logo7.color);
		System.out.println(logo7.shape);
		System.out.println(logo7.name);
		System.out.println(logo7.type);
		System.out.println(logo7.lenght);
		System.out.println(logo7.width);
		System.out.println(logo7.use);
		System.out.println("++++++++++++++++++++");
		Logo logo8=new Logo("White","Round","X-Workz","Company",5.5f,3.5f,"Information","Black");
		System.out.println(logo8.color);
		System.out.println(logo8.shape);
		System.out.println(logo8.name);
		System.out.println(logo8.type);
		System.out.println(logo8.lenght);
		System.out.println(logo8.width);
		System.out.println(logo8.use);
		System.out.println(logo8.color1);
		System.out.println("++++++++++++++++++++");
		Logo logo9=new Logo("White","Round","X-Workz","Company",5.5f,3.5f,"Information","Black","College");
		System.out.println(logo9.color);
		System.out.println(logo9.shape);
		System.out.println(logo9.name);
		System.out.println(logo9.type);
		System.out.println(logo9.lenght);
		System.out.println(logo9.width);
		System.out.println(logo9.use);
		System.out.println(logo9.color1);
		System.out.println(logo9.type1);
	}
}